language: node_js
node_js:
  - "5.6"
before_script: npm run lint
after_script:
  - codeclimate-test-reporter < lcov.info
  - npm run build
addons:
    code_climate:
        repo_token: f06146c07c4c3100bb0cedd256e9202a6bc8d91ad53741f3dd6bc09f60d36273